version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/app:/srv/app:rw
      - ./backend/php/php.ini:/usr/local/etc/php/conf.d/99-security.ini:ro
      - ./backend/php/logs/php-error.log:/srv/logs/php/php-error.log:rw
    working_dir: /srv/app

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/srv/app:ro
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/nginx/logs/error.log:/srv/logs/nginx/error.log:rw
      - ./backend/nginx/logs/access.log:/srv/logs/nginx/access.log:rw
    depends_on:
      - php
