version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: backend/Dockerfile_php
    volumes:
      - ./backend/app:/srv/app:rw
      - ./backend/php/php.ini:/usr/local/etc/php/conf.d/99-security.ini:ro
      - ./backend/php/logs/php-error.log:/srv/logs/php/php-error.log:rw
      - ./backend/php/logrotate:/etc/logrotate.d/funproject-php:ro
    working_dir: /srv/app
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otelcol/config.yaml
      - ./otel-collector/data:/var/log/otel
    ports:
      - "4318:4318"

  nginx:
    build:
      context: .
      dockerfile: backend/Dockerfile_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/srv/app:ro
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/nginx/logs/error.log:/srv/logs/nginx/error.log:rw
      - ./backend/nginx/logs/access.log:/srv/logs/nginx/access.log:rw
      - ./backend/nginx/logrotate:/etc/logrotate.d/funproject-nginx:ro
    depends_on:
      - php
