version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: funproject-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  php:
    build:
      context: .
      dockerfile: backend/Dockerfile_php
    container_name: funproject-php
    volumes:
      - ./backend/app:/srv/app:rw
      - ./backend/php/php.ini:/usr/local/etc/php/conf.d/99-security.ini:ro
      - ./backend/php/logs/php-error.log:/srv/logs/php/php-error.log:rw
      - ./backend/php/logrotate:/etc/logrotate.d/funproject-php:ro
    working_dir: /srv/app
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
      DATABASE_URL: "mysql://app:app@db:3306/app?serverVersion=8.0"
    depends_on:
      - otel-collector
      - db

  otel-collector:
    image: otel/opentelemetry-collector
    container_name: funproject-otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otelcol/config.yaml
      - ./otel-collector/data:/var/log/otel
    ports:
      - "4318:4318"

  nginx:
    build:
      context: .
      dockerfile: backend/Dockerfile_nginx
    container_name: funproject-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/srv/app:ro
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/nginx/logs/error.log:/srv/logs/nginx/error.log:rw
      - ./backend/nginx/logs/access.log:/srv/logs/nginx/access.log:rw
      - ./backend/nginx/logrotate:/etc/logrotate.d/funproject-nginx:ro
    depends_on:
      - php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: funproject-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
